[package]
name = "extendible_hash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.6.2"
crossterm = "0.26.1"
rand = "0.8.5"